### PR TITLE
RLM-307 Add QC test in post-leap

### PR DESCRIPTION
**Pull request by Frank-ZhangXin**
Create a post upgrade playbook to run support QC steps after the upgrade is
complete. This might be run automatically in the gates, but manually in 
customer upgrades.

### CODE REVIEW

**Comment by Frank-ZhangXin** [comment]
recheck_cit_trusty_aio_swift_kilo_to_newton_leap

**Comment by antonym** [comment]
The kilo job will fail until https://github.com/rcbops/rpc-upgrades/pull/41 merges in so should be safe to ignore kilo.

**Comment by antonym** [comment]
Resolved conflict with master.

**Comment by antonym** [comment]
recheck_cit_trusty_aio_swift_kilo_to_newton_leap

**Pull request merged**
