### PR TITLE
Add new component gating skeleton

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
This project is being added to the RE platform. This change adds the
basic structure required to make use of the platform. Please modify
this pull request before merging to enable the required support.
JIRA: RE-1788

### CODE REVIEW

**Comment by mattt416** [comment]
recheck_trusty_aio_swift_liberty_to_newton_leap
recheck_trusty_aio_swift_mitaka_to_newton_leap

**Comment by antonym** [comment]
Mitaka and Liberty gates seem to have been failing for the last week or so when it tries to retrieve Galera packages:

09:47:49 TASK: [galera_server | Drop galera repo pin] ********************************** 
09:47:49 changed: [aio1_galera_container-ce9d30aa]
09:47:49 
09:47:49 TASK: [galera_server | Add galera repo(s)] ************************************ 
09:47:49 ok: [aio1_galera_container-ce9d30aa] => (item={'repo': u'deb http://mirror.rackspace.com/mariadb/repo/10.0/ubuntu trusty main', 'state': 'present'})
09:47:49 changed: [aio1_galera_container-ce9d30aa] => (item={'repo': u'deb http://repo.percona.com/apt trusty main', 'state': 'present'})
09:47:49 
09:47:49 TASK: [galera_server | Download the galera package] *************************** 
09:47:49 failed: [aio1_galera_container-ce9d30aa] => {"attempts": 3, "failed": true}
09:47:49 msg: Task failed as maximum retries was encountered
09:47:49 
09:47:49 FATAL: all hosts have already failed -- aborting

Not sure if it's related to the nodepool image or not, I haven't been able to repro in Vagrant yet.

**Comment by mattt416** [comment]
Hey @antonym , I don't think it's the nodepool image as the PM jobs are failing also and they aren't using nodepool. See https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-upgrades-master-trusty_aio-swift-liberty_to_newton_leap/146/ and https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-upgrades-master-trusty_aio-swift-mitaka_to_newton_leap/18.

**Comment by mattt416** [comment]
recheck_trusty_aio_swift_liberty_to_newton_leap

**Comment by mattt416** [comment]
recheck_trusty_aio_swift_mitaka_to_newton_leap

**Pull request merged**
