### PR TITLE
[RI_598] Enable Vault decryption for incremental upgrades

### PR DESCRIPTION
**Pull request by rexredinger**

### CODE REVIEW

**Comment by rexredinger** [comment]
recheck_xenial_mnaio-snap_swift_newton_to_pike_inc
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by antonym** [comment]
Looks good, might be good to implement the gating testing for vault too:

https://github.com/rcbops/rpc-upgrades/blob/master/tests/test-leapfrog.sh#L27
https://github.com/rcbops/rpc-upgrades/blob/master/tests/test-leapfrog.sh#L33
https://github.com/rcbops/rpc-upgrades/blob/master/tests/test-leapfrog.sh#L54

We could move those up to test-upgrade.sh to reduce duplicate code but it would probably break major and minors.  We could just make those functions too and insert them into the leap and inc statements.

**Comment by antonym** [comment]
2019-02-13T15:27:35-0600 source "test-vault.sh"
2019-02-13T15:27:35-0600 tests/test-incremental.sh: line 19: test-vault.sh: No such file or directory

**Comment by rexredinger** [comment]
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by rexredinger** [comment]
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by rexredinger** [comment]
Hitting [this error](https://docs.sqlalchemy.org/en/latest/errors.html#error-2j85\)/n2019-02-21) during `TASK [os_cinder : Perform a cinder DB sync]` because of deadlocking at the migration from 114 -> 115.

Digging into it more.  I don't think this change set is the cause.

**Comment by antonym** [comment]
Yeah, I see that issue occasionally in gating... just give it a few more rechecks and hopefully it'll clear.

recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by antonym** [comment]
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by rexredinger** [comment]
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by antonym** [comment]
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by antonym** [comment]
I'm guessing there were some deadlock issue fixes in cinder from November which the code should have, so maybe they aren't all fixed.

https://review.openstack.org/#/c/629059/

recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by rexredinger** [comment]
From Cinder upgrade documentation:
> Adding a Column: This is the simplest case - we don’t have any requirements when adding a new column apart from the fact that it should be added as the last one in the table. If that’s covered, the DB engine will make sure the migration won’t be disruptive.

That does not the case for migration [115](https://github.com/openstack/cinder/blob/4bb00dbcf6af2f140694eb535696f0f6fe3ae80e/cinder/db/sqlalchemy/migrate_repo/versions/115_add_shared_targets_to_volumes.py) and likely migrations 116 and 123.  I'm wondering if setting a default value in the column does something wonky.

recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by antonym** [comment]
recheck_xenial_mnaio-snap_swift_pike_to_queens_inc

**Comment by rexredinger** [comment]
xenial_mnaio-snap_swift_pike_to_queens_inc appears to have actually failed for a legitimate reason this time.

> 2019-02-26T18:41:40-0600 vault_encrypt_secrets
> 2019-02-26T18:41:40-0600 Checking to see if user_secrets.yml needs to be encrypted...
> 2019-02-26T18:41:41-0600 Usage: ansible-vault encrypt [options] file_name
> 2019-02-26T18:41:41-0600 
> 2019-02-26T18:41:41-0600 encryption/decryption utility for Ansible data files
> 2019-02-26T18:41:41-0600 
> 2019-02-26T18:41:41-0600 Options:
> 2019-02-26T18:41:41-0600   --ask-vault-pass      ask for vault password
> ...
> 2019-02-26T18:41:41-0600 command.
> 2019-02-26T18:41:41-0600 ERROR! Only one --vault-id can be used for encryption. This includes passwords from configuration and cli.

**Pull request closed without merging**
