### PR TITLE
Update configure-lxc-backend.yml

### PR DESCRIPTION
**Pull request by brewc**
fix lxc-backend _osa_config conditional

### CODE REVIEW

**Comment by BjoernT** [comment]
What error did you see, is success actually replaces the old jinja style notation (|success)

**Comment by brewc** [comment]
Hmm.  I must have done something wrong here.  I reverted my change and am upgrading to Rocky in my AIO and im not seeing the error anymore.  I wonder if it is ansible/python dependent.

**Comment by brewc** [comment]
TASK [Find overrides file] *****************************************************
Saturday 01 May 2021  21:52:42 +0000 (0:00:00.035)       0:00:02.250 **********
^[[0;31mfatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '_osa_config is success' failed. The error was: template error while templating string: no test named 'success'. String: {% if _osa_config is success %} True {% else %} False {% endif %}"}^[[0m

**Comment by BjoernT** [comment]
Closing for now

**Pull request closed without merging**
