### PR TITLE
RLM-292 Add second leapfrog run to gating

### PR DESCRIPTION
**Pull request by antonym**
To ensure leapfrog is idempotent.

### CODE REVIEW

**Comment by Frank-ZhangXin** [comment]
recheck_continuous_integration_travis_ci_pr

**Comment by antonym** [comment]
recheck_cit_trusty_aio_swift_kilo_to_newton_leap

**Comment by antonym** [comment]
Went ahead and included RLM-293 in this patch so we can test both out.

**Comment by antonym** [comment]
@claco Tests pass and include the qc-check now.

**Pull request merged**
