### PR TITLE
RE-1162 Remove legacy .travis.yml file

### PR DESCRIPTION
**Pull request by mattt416**
This commit removes the .travis.yml, and also passes a custom workdir
to tox to avoid failures where files in tox's venvs have excessively
long shebang lines.  At present, we're hitting such an issue with [1]
which is causing the job to fail in the most cryptic way possible.

Thanks to @git-harry for the fix.

[1] PR_rpc-upgrades-master-container-ansible-syntax-tox-test

### CODE REVIEW

**Comment by mattt416** [comment]
This needs to merge after https://github.com/rcbops/rpc-gating/pull/613 merges.

**Comment by hughsaunders** [comment]
rcbops/rpc-gating#613 has now merged, waiting for jobs to be created before merging this.

**Comment by git-harry** [comment]
recheck_container_ansible-lint_tox-test
recheck_container_ansible-syntax_tox-test
recheck_container_bashate_tox-test
recheck_container_docs_tox-test
recheck_container_pep8_tox-test
recheck_container_releasenotes_tox-test

**Comment by mattt416** [comment]
recheck_all

**Comment by mattt416** [comment]
recheck_cit_container_ansible-syntax_tox-test

**Comment by mattt416** [comment]
recheck_cit_container_ansible-syntax_tox-test

**Comment by antonym** [comment]
@git-harry I've enabled the new ones to be required now.

**Pull request merged**
